version: '3.8'

services:
  mugen:
    build:
      context: .
      dockerfile: Dockerfile.dev
      tags:
        - 'mugen:latest'
    container_name: mugen-app
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NEXT_WEBPACK_USEPOLLING=1
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
